import { WorldConfig } from '../types/world';

export const HUB_WORLDS: WorldConfig[] = [
  // Developer Field
  {
    id: 'terminal-office',
    slug: 'terminal-office',
    name: 'Terminal Office',
    field: 'developer',
    styleTier: 'regular-ish',
    archetype: 'Systems & Backend Architect',
    tagline: 'Text-based command workspace for systems builders',
    description: 'A bespoke command line interface showcasing developer case studies through an interactive unix terminal parser.',
    portalGlyph: '>_',
    portalColor: '#10b981',
    accentColor: '#34d399',
    bgColor: '#060d09',
    soundtrackMood: 'terminal',
    projects: [
      {
        id: 'term-p1',
        title: 'Distributed Transaction Mesh Engine',
        clientType: 'Fintech Infrastructure Lead',
        category: 'High-Throughput Distributed Systems',
        year: '2025',
        summary: 'Zero-downtime ledger synchronization handling 120,000 TPS across hybrid multi-region clusters.',
        description: 'Engineered an asynchronous Raft consensus engine in Rust with customized LSM storage trees for sub-millisecond execution times.',
        deliverables: ['Custom Consensus Protocol', 'WASM Benchmarking Suite', 'Real-time Metrics Daemon'],
        techOrTools: ['Rust', 'Tokio', 'Raft Protocol', 'gRPC', 'Prometheus'],
        tags: ['Distributed Systems', 'Low Latency', 'Infrastructure'],
        metricsOrHighlight: '120k peak TPS with p99 latency < 4.2ms across AWS and on-premise clusters.',
        repoUrl: 'https://github.com/example/transaction-mesh',
      },
      {
        id: 'term-p2',
        title: 'Autonomous Code Refactoring Agent',
        clientType: 'AI Developer Tooling Startup',
        category: 'LLM Systems & Compiler Tooling',
        year: '2025',
        summary: 'Graph-guided AST transformer transforming legacy monolithic codebases into modular micro-packages.',
        description: 'Combined Tree-sitter semantic graphs with local LLM verification loops to generate verified regression-tested pull requests.',
        deliverables: ['AST Dependency Parser', 'Automated Verification Pipeline', 'CLI Tooling Suite'],
        techOrTools: ['TypeScript', 'Tree-sitter', 'Python', 'Docker', 'Ollama'],
        tags: ['AI Agent', 'Compilers', 'Developer Tools'],
        metricsOrHighlight: 'Successfully decoupled 85,000 LOC legacy codebases with 100% test preservation.',
        repoUrl: 'https://github.com/example/refactor-agent',
      },
      {
        id: 'term-p3',
        title: 'Zero-Knowledge Identity Attestation',
        clientType: 'Privacy-Preserving Web3 Protocol',
        category: 'Cryptographic Protocols',
        year: '2024',
        summary: 'Private identity verification without exposing personal credential payloads or biometric markers.',
        description: 'Implemented zk-SNARK circuits in Circom, compiled into ultra-lightweight client-side verification proofs executing in web workers.',
        deliverables: ['Circom Verification Circuits', 'Client Proof SDK', 'Security Audit Dossier'],
        techOrTools: ['Circom', 'SnarkJS', 'Solidity', 'WebAssembly'],
        tags: ['Cryptography', 'Privacy', 'ZK-Proofs'],
        metricsOrHighlight: 'Generated client-side verification proofs in under 1.8 seconds on standard mobile browsers.',
        repoUrl: 'https://github.com/example/zk-identity-circuits',
      },
    ],
  },
  {
    id: 'retro-workstation',
    slug: 'retro-workstation',
    name: 'Retro Workstation',
    field: 'developer',
    styleTier: 'crazy',
    archetype: 'Full-Stack Creative Technologist',
    tagline: 'Interactive 3D CRT desk with draggable retro desktop windows',
    description: 'An interactive virtual machine environment with custom window managers and nostalgic computing aesthetics.',
    portalGlyph: 'CRT',
    portalColor: '#38bdf8',
    accentColor: '#60a5fa',
    bgColor: '#090d16',
    soundtrackMood: 'retro-workstation',
    projects: [
      {
        id: 'cpu-p1',
        title: 'CyberDeck In-Browser Emulator',
        clientType: 'Retrocomputing Hardware Preservationist',
        category: 'Virtual Machine Architecture',
        year: '2025',
        summary: 'Full cycle-accurate x86 hardware emulator running classic graphical operating systems directly in browser Web Workers.',
        description: 'Built with C++ compiled to WebAssembly with custom VGA framebuffers and virtual floppy disk controllers.',
        deliverables: ['Cycle-accurate CPU Core', 'Audio DSP Synth', 'WebAssembly Bridge'],
        techOrTools: ['WebAssembly', 'C++', 'WebGL', 'Web Audio API'],
        tags: ['Emulation', 'WebAssembly', 'Low-Level'],
        metricsOrHighlight: 'Sustains seamless 60fps VGA rendering directly in mobile browser viewports.',
        repoUrl: 'https://github.com/example/cyberdeck-emu',
      },
      {
        id: 'cpu-p2',
        title: 'Pixel-Craft Collaborative Engine',
        clientType: 'Indie Game Collective',
        category: 'Real-time Multiplayer Canvas',
        year: '2025',
        summary: 'Multi-user infinite sprite canvas with deterministic state rollback and low-bandwidth delta compression.',
        description: 'WebRTC data-channel mesh with CRDT resolution for instantaneous creative collaboration without server lag.',
        deliverables: ['Real-time CRDT Protocol', 'Pixel Engine Canvas', 'Asset Exporter'],
        techOrTools: ['TypeScript', 'WebRTC', 'Canvas 2D', 'Yjs', 'Node.js'],
        tags: ['Multiplayer', 'Creative Tools', 'Real-time'],
        metricsOrHighlight: 'Supported 500 concurrent artists in a shared room with zero state divergence.',
        repoUrl: 'https://github.com/example/pixel-craft',
      },
      {
        id: 'cpu-p3',
        title: 'Vintage Synth Sequencer & Tracker',
        clientType: 'Electronic Music Producer',
        category: 'Audio Software Instrument',
        year: '2024',
        summary: 'Chiptune tracker with FM synthesis, 16-step polyphonic patterns, and automated MIDI controller mapping.',
        description: 'Pure procedural audio engine simulating vintage soundchips with wavetable modulation.',
        deliverables: ['Custom Web Audio Synth', 'Pattern Sequencer', 'MIDI Export Engine'],
        techOrTools: ['Web Audio API', 'React', 'AudioWorklet', 'Web MIDI'],
        tags: ['Audio DSP', 'Music Tech', 'Synthesizer'],
        metricsOrHighlight: 'Zero-latency jitter with dedicated AudioWorklet thread scheduling.',
        repoUrl: 'https://github.com/example/retro-tracker',
      },
    ],
  },
  {
    id: 'silicon-matrix',
    slug: 'silicon-matrix',
    name: 'Silicon Matrix',
    field: 'developer',
    styleTier: 'out of this universe',
    archetype: 'Hardware & Embedded Firmware Engineer',
    tagline: 'Glow-traced motherboard landscape with interactive integrated circuit nodes',
    description: 'An expansive circuit board world where copper traces transmit pulses between projects on integrated microchips.',
    portalGlyph: 'PCB',
    portalColor: '#f59e0b',
    accentColor: '#fbbf24',
    bgColor: '#0a0904',
    soundtrackMood: 'silicon-matrix',
    projects: [
      {
        id: 'circ-p1',
        title: 'Sub-Watt Edge AI Neural Accelerator',
        clientType: 'Robotics & Drone Manufacturer',
        category: 'Embedded Systems & FPGA',
        year: '2025',
        summary: 'Ultra-low-power computer vision processor deployed on customized RISC-V silicon cores.',
        description: 'Designed quantized 4-bit convolutional layers operating in micro-watt power budgets for autonomous drone collision avoidance.',
        deliverables: ['Verilog Hardware Description', 'Firmware Driver Core', 'TensorRT Pipeline'],
        techOrTools: ['RISC-V', 'Verilog', 'C', 'TensorRT', 'Embedded Linux'],
        tags: ['Hardware', 'Edge AI', 'FPGA'],
        metricsOrHighlight: 'Reduced processing wattage by 78% while sustaining 45 FPS inference.',
        repoUrl: 'https://github.com/example/edge-neural-accel',
      },
      {
        id: 'circ-p2',
        title: 'Biometric Wearable Telemetry Node',
        clientType: 'MedTech Sensor Pioneer',
        category: 'IoT Sensor Firmware',
        year: '2024',
        summary: 'Continuous ECG and blood oxygen telemetry monitor running FreeRTOS with encrypted BLE broadcasting.',
        description: 'Implemented hardware interrupt-driven sensor sampling with AES-GCM 256-bit encryption on Nordic nRF5340 chips.',
        deliverables: ['FreeRTOS Firmware', 'BLE Cryptographic Protocol', 'Power Management Schema'],
        techOrTools: ['C++', 'FreeRTOS', 'BLE 5.3', 'Nordic SDK', 'Altium Designer'],
        tags: ['Firmware', 'IoT', 'Medical'],
        metricsOrHighlight: 'Extended battery lifespan from 4 days to 28 days on single coin-cell battery.',
        repoUrl: 'https://github.com/example/biometric-telemetry',
      },
      {
        id: 'circ-p3',
        title: 'High-Density PCB Flight Controller',
        clientType: 'Aerospace Research Lab',
        category: 'Avionics Hardware',
        year: '2024',
        summary: '6-layer impedance-matched flight control motherboard with dual redundant IMUs and CAN bus diagnostics.',
        description: 'Engineered high-frequency trace routing with EMI shielding cages for high-vibration aerospace launches.',
        deliverables: ['6-Layer PCB Schematic', 'Thermal Dissipation Models', 'Firmware Bootloader'],
        techOrTools: ['KiCad', 'CAN Bus', 'STM32', 'ARM Cortex-M7'],
        tags: ['PCB Design', 'Aerospace', 'Hardware'],
        metricsOrHighlight: 'Passed 10G vibration stress tests with 0 data packet corruption.',
        repoUrl: 'https://github.com/example/flight-pcb-matrix',
      },
    ],
  },

  // Designer Field
  {
    id: 'curator-monolith',
    slug: 'curator-monolith',
    name: 'Curator Monolith',
    field: 'designer',
    styleTier: 'regular-ish',
    archetype: 'Brand Identity & Exhibition Designer',
    tagline: 'Serene white museum gallery with generous whitespace and framed prints',
    description: 'An architectural gallery space honoring fine typography, sculptural layouts, and large format exhibition portfolios.',
    portalGlyph: 'ART',
    portalColor: '#e2e8f0',
    accentColor: '#f8fafc',
    bgColor: '#12141a',
    soundtrackMood: 'curator-monolith',
    projects: [
      {
        id: 'gal-p1',
        title: 'Nordic Architecture Biennial Identity',
        clientType: 'International Cultural Foundation',
        category: 'Brand Identity & Wayfinding',
        year: '2025',
        summary: 'Complete visual identity system, architectural exhibition signage, and custom variable grotesque typography.',
        description: 'Conceived a stark typographic framework informed by Scandinavian daylight cycles, extending across 14 exhibition pavilions.',
        deliverables: ['Bespoke Variable Typeface', 'Wayfinding Signage System', 'Exhibition Catalog (400 pages)'],
        techOrTools: ['Glyphs 3', 'Adobe InDesign', 'Cinema 4D', 'Figma'],
        tags: ['Typography', 'Identity', 'Exhibition'],
        metricsOrHighlight: 'Awarded Red Dot Best of the Best 2025 in Visual Communication.',
        liveUrl: 'https://example.com/nordic-biennial',
      },
      {
        id: 'gal-p2',
        title: 'Lumina Haute Horlogerie Digital Sanctuary',
        clientType: 'Swiss Luxury Timepiece Maison',
        category: 'Luxury E-Commerce & Art Direction',
        year: '2025',
        summary: 'An editorial digital flagship celebrating artisanal mechanical complications and micro-engineering.',
        description: 'Designed serene spatial interactions with macro 3D watch teardowns and refined typography that mirrors Swiss craft heritage.',
        deliverables: ['Art Direction Guidelines', 'E-Commerce Experience Architecture', 'Interactive Complication Visualizer'],
        techOrTools: ['Figma', 'Three.js', 'Next.js', 'Tailwind'],
        tags: ['Luxury', 'Art Direction', 'Web Design'],
        metricsOrHighlight: 'Increased international client engagement duration by 310%.',
        liveUrl: 'https://example.com/lumina-watches',
      },
      {
        id: 'gal-p3',
        title: 'Atelier Kanso Minimal Furniture Monograph',
        clientType: 'Kyoto Woodworking Studio',
        category: 'Publication & Packaging Design',
        year: '2024',
        summary: 'Tactile print monograph bound in raw Japanese washi paper with blind deboss foil and silver-leaf detailing.',
        description: 'Documented 40 years of joinery philosophy with austere black-and-white photography and bilingual Japanese/English typesetting.',
        deliverables: ['Hardcover Monograph', 'Custom Linen Slipcase', 'Short Documentary Film Art Direction'],
        techOrTools: ['InDesign', 'Lightroom', 'Custom Paper Engineering'],
        tags: ['Editorial', 'Print', 'Packaging'],
        metricsOrHighlight: 'Limited run of 1,500 copies sold out within 72 hours of gallery opening.',
        liveUrl: 'https://example.com/kanso-monograph',
      },
    ],
  },
  {
    id: 'torn-atelier',
    slug: 'torn-atelier',
    name: 'Torn Atelier',
    field: 'designer',
    styleTier: 'crazy',
    archetype: 'Editorial & Experimental Typographer',
    tagline: 'Scattered sketchbook pages with torn edges, hand annotations, and organic parallax',
    description: 'An intimate creative workshop where ideas are scattered across torn craft paper, washi tape, and pencil doodles.',
    portalGlyph: 'RAW',
    portalColor: '#f97316',
    accentColor: '#fb923c',
    bgColor: '#16100c',
    soundtrackMood: 'torn-atelier',
    projects: [
      {
        id: 'sketch-p1',
        title: 'Dadaist Manifesto: Kinetic Poster Series',
        clientType: 'Experimental Arts Press',
        category: 'Experimental Graphic Design',
        year: '2025',
        summary: 'Risograph-printed kinetic posters combining destructive collages, xerox burns, and reactive typography.',
        description: 'Crafted through manual analog scanning, physical paper tearing, and digital vector recombination to celebrate anti-rules aesthetics.',
        deliverables: ['12 Screenprinted Posters', 'AR Motion Companion App', 'Type Specimen Zine'],
        techOrTools: ['Risograph Printing', 'After Effects', 'Illustrator', 'Physical Collage'],
        tags: ['Poster Design', 'Experimental', 'Collage'],
        metricsOrHighlight: 'Featured in Tokyo TDC Annual 2025 and exhibited across 4 international galleries.',
        liveUrl: 'https://example.com/dada-posters',
      },
      {
        id: 'sketch-p2',
        title: 'The Underground Botanical Field Journal',
        clientType: 'Independent Herbalist Guild',
        category: 'Book Design & Scientific Illustration',
        year: '2024',
        summary: 'A 240-page illustrated encyclopedia of subterranean fungi and mosses styled as an explorer’s lost field notebook.',
        description: 'Combines hand-penciled botanical diagrams, watercolor washes, and stamped botanical taxonomy tables.',
        deliverables: ['Hand-bound Field Journal', 'Watercolor Palette Guide', 'Die-cut Herbarium Inserts'],
        techOrTools: ['Graphite Drawing', 'Watercolors', 'InDesign', 'Photoshop'],
        tags: ['Illustration', 'Editorial', 'Bookbinding'],
        metricsOrHighlight: 'Funded at 640% on Kickstarter with over 4,000 backer collectors.',
        liveUrl: 'https://example.com/botanical-journal',
      },
      {
        id: 'sketch-p3',
        title: 'Punk Record Label Sonic Identity System',
        clientType: 'Independent Vinyl Label',
        category: 'Music Packaging & Merch Ecosystem',
        year: '2024',
        summary: 'Lo-fi photocopier cassette inserts, vinyl gatefolds, and embroidered patch collections for 8 debut indie records.',
        description: 'Built on halftone dots, gritty photocopy textures, distorted ransom-note typography, and raw screen-printed cardboard.',
        deliverables: ['Gatefold Vinyl Packaging', 'Cassette J-Cards', 'Tour Merchandise Collection'],
        techOrTools: ['Screen Printing', 'Photocopy Distortion', 'Illustrator'],
        tags: ['Music', 'Vinyl', 'Packaging'],
        metricsOrHighlight: 'Produced over 10,000 physical vinyl and cassette units distributed globally.',
        liveUrl: 'https://example.com/punk-vinyl',
      },
    ],
  },
  {
    id: 'pigment-nebula',
    slug: 'pigment-nebula',
    name: 'Pigment Nebula',
    field: 'designer',
    styleTier: 'out of this universe',
    archetype: 'Digital Artist & Color Theorist',
    tagline: 'Living procedural oil-stroke universe with orbiting painted project bodies',
    description: 'A fluid cosmic dimension of swirling gouache, acrylic impasto, and floating celestial paint strokes that warp on proximity.',
    portalGlyph: 'HUE',
    portalColor: '#ec4899',
    accentColor: '#f472b6',
    bgColor: '#140612',
    soundtrackMood: 'pigment-nebula',
    projects: [
      {
        id: 'paint-p1',
        title: 'Chromatophores: Living Generative Color Field',
        clientType: 'Digital Art Museum Pavilion',
        category: 'Generative Interactive Installation',
        year: '2025',
        summary: 'Real-time multi-sensory color field that computes fluid dynamics based on visitor foot traffic and acoustic presence.',
        description: 'Developed custom Navier-Stokes fluid simulations rendered with custom raymarching shaders on 8K LED walls.',
        deliverables: ['Real-time GLSL Shader Suite', 'Kinect Tracking Integration', 'Spatial Audio Synchronization'],
        techOrTools: ['GLSL Shaders', 'TouchDesigner', 'C++', 'OpenFrameworks'],
        tags: ['Generative Art', 'Interactive', 'Shaders'],
        metricsOrHighlight: 'Experienced by over 350,000 museum attendees during the 6-month pavilion run.',
        liveUrl: 'https://example.com/chromatophores',
      },
      {
        id: 'paint-p2',
        title: 'Aura Synthesis: Luxury Fragrance Visuals',
        clientType: 'Parisian Niche Perfumery',
        category: 'Digital Scent Visualization & 3D',
        year: '2025',
        summary: 'Translating ephemeral olfactory notes (vetiver, bergamot, iris) into iridescent swirling fluid micro-universes.',
        description: 'Created dynamic fluid procedural simulations and macro droplet renders for digital campaign films and flagship screens.',
        deliverables: ['5 Hero 3D Fluid Films', 'Interactive Scent Explorer Web App', 'Visual Identity Packaging'],
        techOrTools: ['Houdini', 'Octane Render', 'Three.js', 'Cinema 4D'],
        tags: ['3D Fluid', 'Luxury', 'Visual Effects'],
        metricsOrHighlight: 'Campaign video achieved over 12 million views across global design channels.',
        liveUrl: 'https://example.com/aura-synthesis',
      },
      {
        id: 'paint-p3',
        title: 'Prismatic Symphony: Audio-Reactive Album Cover',
        clientType: 'Ambient Electronic Composer',
        category: 'Dynamic Generative Vinyl Art',
        year: '2024',
        summary: 'Procedural generative artwork that mutates its brushstroke density based on the audio frequency spectrum of each track.',
        description: 'Wrote WebGL shaders computing impasto pigment depth, oil glossiness, and chromatic dispersion modulated by audio stems.',
        deliverables: ['Generative Art Generator', 'Interactive Web Vinyl Player', 'High-Res Print Master'],
        techOrTools: ['WebGL', 'Web Audio API', 'React', 'GLSL'],
        tags: ['Music Visualizer', 'Generative', 'WebGL'],
        metricsOrHighlight: 'Each listener generated a unique mathematically distinct 1-of-1 vinyl artwork.',
        liveUrl: 'https://example.com/prismatic-symphony',
      },
    ],
  },

  // Illustrator and Comic Artist Field
  {
    id: 'graphic-chronicle',
    slug: 'graphic-chronicle',
    name: 'Graphic Chronicle',
    field: 'illustrator',
    styleTier: 'regular-ish',
    archetype: 'Graphic Novelist & Sequential Storyteller',
    tagline: 'Scrolling comic strip with snapping panels, Ben-Day halftone dots, and SFX bubbles',
    description: 'A dynamic comic book reading experience with bold ink borders, dialogue balloons, and punchy pop-art sound effect overlays.',
    portalGlyph: 'POW!',
    portalColor: '#ef4444',
    accentColor: '#f87171',
    bgColor: '#140808',
    soundtrackMood: 'graphic-chronicle',
    projects: [
      {
        id: 'comic-p1',
        title: 'Neon Ronin: Cyberpunk Graphic Novel (Vol. 1)',
        clientType: 'Dark Horse / Independent Release',
        category: 'Graphic Novel & Character Design',
        year: '2025',
        summary: 'A 180-page serialized graphic novel following a rogue cybernetic detective through flooded subterranean megalopolises.',
        description: 'Hand-inked with traditional G-pen brushes and colored with high-energy neon Ben-Day screentones and custom speedlines.',
        deliverables: ['180 Illustrated Comic Pages', 'Cover Art Variant Editions', 'Character Concept Art Bible'],
        techOrTools: ['Clip Studio Paint', 'G-Pen Traditional Inks', 'Photoshop', 'InDesign'],
        tags: ['Comics', 'Sequential Art', 'Cyberpunk'],
        metricsOrHighlight: 'Nominated for Best New Graphic Novel at the 2025 Comic Arts Festival.',
        liveUrl: 'https://example.com/neon-ronin',
      },
      {
        id: 'comic-p2',
        title: 'The Clockwork Alchemist: Webtoon Epic',
        clientType: 'Digital Webtoon Publisher',
        category: 'Vertical Scroll Webcomic',
        year: '2025',
        summary: 'High-octane steampunk fantasy webcomic engineered specifically for seamless vertical mobile scrolling.',
        description: 'Optimized pacing, dramatic cliffhanger gutters, and vivid cinematic lighting tuned for OLED mobile displays.',
        deliverables: ['40 Serialized Episodes', 'Promotional Teaser Animations', 'Merchandise Sticker Packs'],
        techOrTools: ['Clip Studio Paint', 'Procreate', 'Blender 3D Backgrounds'],
        tags: ['Webcomic', 'Steampunk', 'Illustration'],
        metricsOrHighlight: 'Amassed over 1.4 million weekly readers across digital platforms.',
        liveUrl: 'https://example.com/clockwork-alchemist',
      },
      {
        id: 'comic-p3',
        title: 'Kaiju Protocol: Tabletop RPG Storyboard',
        clientType: 'Board Game Studio',
        category: 'TTRPG Worldbuilding & Character Cards',
        year: '2024',
        summary: 'Over 80 dramatic monster encounters, pilot battle portraits, and dynamic scenario comic cutscenes for a giant mecha board game.',
        description: 'High-contrast ink crosshatching and dramatic camera angles reminiscent of vintage 1970s manga.',
        deliverables: ['80 Illustrated Encounter Cards', 'Rulebook Comic Prologue', 'Game Board Illustration'],
        techOrTools: ['Traditional Ink Washes', 'Clip Studio Paint', 'Illustrator'],
        tags: ['Board Game', 'Mecha', 'Character Design'],
        metricsOrHighlight: 'Board game campaign surpassed $800k in crowdfunding within 48 hours.',
        liveUrl: 'https://example.com/kaiju-protocol',
      },
    ],
  },
  {
    id: 'origami-vault',
    slug: 'origami-vault',
    name: 'Origami Vault',
    field: 'illustrator',
    styleTier: 'crazy',
    archetype: 'Paper Engineer & Children’s Book Artist',
    tagline: 'Interactive 3D pop-up book unfolding with physical paper depth and creases',
    description: 'An enchanting paper-crafted book where turning pages unfolds multi-layered 3D cutouts, dioramas, and papercraft architecture.',
    portalGlyph: 'FOLD',
    portalColor: '#a855f7',
    accentColor: '#c084fc',
    bgColor: '#100a18',
    soundtrackMood: 'origami-vault',
    projects: [
      {
        id: 'popup-p1',
        title: 'The Forest of Wonders: 3D Papercraft Bestiary',
        clientType: 'Museum of Natural History / Children’s Imprint',
        category: 'Dimensional Book & Paper Engineering',
        year: '2025',
        summary: 'A masterwork pop-up book featuring 6 complex mechanical unfolding habitats: rainforests, coral reefs, and arctic tundras.',
        description: 'Engineered intricate paper pull-tabs, pivot hinges, and multi-tier pop-up silhouettes with zero plastic components.',
        deliverables: ['6 Mechanical Pop-up Spreads', 'Die-cut Template Production Files', 'Hand-cut Proof Models'],
        techOrTools: ['Paper Engineering', 'Laser Cutting CAD', 'Gouache Painting', 'Cardstock Craft'],
        tags: ['Paper Engineering', 'Children Books', '3D Diorama'],
        metricsOrHighlight: 'Winner of the Movable Book Society Meggendorfer Prize 2025.',
        liveUrl: 'https://example.com/forest-wonders',
      },
      {
        id: 'popup-p2',
        title: 'Chronos Clocktower: Pop-Up Architecture Kit',
        clientType: 'Maker Toy & Puzzle Manufacturer',
        category: 'Architectural Papercraft Kit',
        year: '2025',
        summary: 'Self-assembling mechanical clocktower kit with working paper gears, pendulum escapement, and fold-out stained glass windows.',
        description: 'Designed interlocking precision tabs allowing builders to assemble a 45cm high pop-up cathedral without glue.',
        deliverables: ['Interlocking Die-cut Sheets', 'Illustrated Assembly Manual', 'Packaging Box Design'],
        techOrTools: ['Vector CAD', 'Cardboard Prototyping', 'Rhino 3D', 'Illustrator'],
        tags: ['Papercraft', 'Puzzle', 'Architecture'],
        metricsOrHighlight: 'Manufactured and shipped to over 30,000 hobbyists globally.',
        liveUrl: 'https://example.com/chronos-clocktower',
      },
      {
        id: 'popup-p3',
        title: 'Shadow Theatre: Fairytale Lightbox Collection',
        clientType: 'Theatrical Puppetry Festival',
        category: 'Layered Shadowbox Diorama',
        year: '2024',
        summary: 'A series of 8 laser-cut paper dioramas lit from behind by warm LEDs, illustrating European folk tales in delicate silhouette.',
        description: 'Constructed using 12 staggered cardstock planes creating deep natural cast shadows and theatrical atmospheric perspective.',
        deliverables: ['8 Backlit Paper Dioramas', 'Limited Edition Art Prints', 'Stage Shadow Puppets'],
        techOrTools: ['Laser Cutting', 'Silhouette Illustration', 'LED Electronics'],
        tags: ['Shadowbox', 'Storytelling', 'Cut Paper'],
        metricsOrHighlight: 'Exhibited in the permanent collection of the International Puppet Theatre Center.',
        liveUrl: 'https://example.com/shadow-theatre',
      },
    ],
  },
  {
    id: 'monochrome-rift',
    slug: 'monochrome-rift',
    name: 'Monochrome Rift',
    field: 'illustrator',
    styleTier: 'out of this universe',
    archetype: 'Sumi-e & Dark Ink Surrealist',
    tagline: 'Infinite black-and-white ink dimension of falling strokes and living ink wash',
    description: 'A hypnotic abyss where fluid black ink bleeds across white void without comic borders, where paintings drift as living surreal scenes.',
    portalGlyph: 'INK',
    portalColor: '#94a3b8',
    accentColor: '#e2e8f0',
    bgColor: '#000000',
    soundtrackMood: 'monochrome-rift',
    projects: [
      {
        id: 'ink-p1',
        title: 'The Obsidian Dream: Animated Inkwash Odyssey',
        clientType: 'Avant-Garde Film Festival',
        category: 'Hand-Drawn Animated Short',
        year: '2025',
        summary: 'A 14-minute meditative animated short drawn entirely with real Sumi-e pine soot ink on rice paper, animated at 24fps.',
        description: 'Over 4,200 individual ink wash paintings exploring metamorphosis, solitude, and celestial tides without dialogue or spoken word.',
        deliverables: ['4,200 Physical Ink Paintings', '4K Digital Film Master', 'Original Score Art Direction'],
        techOrTools: ['Sumi-e Brushwork', 'Rice Paper', 'Dragon Stop Motion', 'DaVinci Resolve'],
        tags: ['Traditional Animation', 'Sumi-e', 'Film'],
        metricsOrHighlight: 'Official Selection at Annecy International Animation Festival 2025.',
        liveUrl: 'https://example.com/obsidian-dream',
      },
      {
        id: 'ink-p2',
        title: 'Yokai Shadows: Surreal Mythological Bestiary',
        clientType: 'Fine Art Print Publisher',
        category: 'Large-Format Fine Art Etchings',
        year: '2025',
        summary: 'A suite of 20 colossal 1.5-meter copperplate etchings depicting forgotten folklore spirits emerging from dark mist.',
        description: 'Mastery of intense aquatint, deep drypoint scratches, and rich oil-based carbon black inks printed on heavy French cotton rag.',
        deliverables: ['20 Copperplate Etching Editions', 'Archival Portfolio Box', 'Exhibition Monograph'],
        techOrTools: ['Copperplate Etching', 'Aquatint', 'Intaglio Printing Press'],
        tags: ['Fine Art', 'Printmaking', 'Mythology'],
        metricsOrHighlight: 'Acquired by the National Museum of Modern Art print collection.',
        liveUrl: 'https://example.com/yokai-shadows',
      },
      {
        id: 'ink-p3',
        title: 'Echoes of the Abyss: Interactive Ink Cavern',
        clientType: 'Sensory Art Laboratory',
        category: 'Audio-Reactive Spatial Ink Canvas',
        year: '2024',
        summary: 'A 360-degree interactive virtual space where whispers and microphone input cause ink to dissolve and reform into surreal landscapes.',
        description: 'High-contrast real-time fluid simulation of diffusion-limited aggregation and ink wash bleeding on virtual fibrous textures.',
        deliverables: ['Spatial Interactive WebGL Engine', 'Microphone Acoustic DSP Hook', 'Ambient Audio System'],
        techOrTools: ['WebGL', 'GLSL Fluid Bleed', 'Three.js', 'Web Audio API'],
        tags: ['Interactive Art', 'Black & White', 'Shaders'],
        metricsOrHighlight: 'Over 500,000 online visitors with average interactive session of 14 minutes.',
        liveUrl: 'https://example.com/echoes-abyss',
      },
    ],
  },
];
